export interface navigate_linkInterface {
    "sign_in": string,
    "sign_up": string,
    "home": string,
    "profile": string,
    "account_information": string,
    "privacy_policy": string,
    "terms_condition": string,
    "notifications": string,
    "orders": string,
    "wishlists": string,
    "carts": string,
    "shipping_address": string,
    "support_tickets": string,
    "settings": string,
    "search": string,
    "browser_history": string,
}
export const navigate_link: navigate_linkInterface = {
    sign_in: "/sign-in",
    search: "/search",
    sign_up: "/sign-up",
    home: "/home",
    profile: "/profile",
    account_information: "/account-information",
    privacy_policy: '/privacy-policy',
    terms_condition: '/terms-condition',
    browser_history: '/browser-history',
    carts: '/carts',
    notifications: '/notifications',
    orders: '/orders',
    wishlists: '/wishlists',
    shipping_address: '/shipping-address',
    support_tickets: "/support-tickets",
    settings: '/settings'
}
