export interface translateInterface {
    "home": string,
    "wishlist": string,
    "cart": string,
    "add_new_address": string,
    "profile": string,
    "account_information": string,
    "notifications": string,
    "my_orders": string,
    "my_carts": string,
    "search": string,
    "update": string,
    "go_back": string,
    "my_wishlists": string,
    "shipping_address": string,
    "support_tickets": string,
    "select_city": string,
    "select_area": string,
    "my_profile": string,
    "area_address": string,
    "settings": string,
    "address_label": string,
    "log_out": string,
    "name": string,
    "email": string,
    "balance": string,
    "courier_service_address": string,
    "birthday": string,
    "country": string,
    "default_shipping_address": string,
    "gender": string,
    "is_block": string,
    "last_login": string,
    "phone": string,
    "registered": string,
    "reward_coins": string,
    "user_id": string,
    "user_type": string,
    "change_language": string,
    "details": string,
    "tracking_number": string,
    "total_amount": string,
    "buy_now": string,
    "courier_address": string,
    "default_address": string,
    "terms": string,
    "cancel": string,
    "search_for_something": string,
    "no_results_found": string,

    "exit": string,
    "browser_history": string,

    "privacy_policy": string,
    "by_signing_up_i_agree_to_the_terms_and_privacy_policy": string,
    "sign_in": string,
    "already_have_account": string,
    "sign_up": string,
    "password_error": string,
    "new_here": string,
    "email_error": string,
    "password": string,
    "enter_valid_info_of_area_address": string,
    "forget_my_password": string,
    "phone_error": string,
    "name_error": string,
    "do_you_want_to_exit": string,
    "alternate_phone_number": string,
}

export const translate: { bn: translateInterface, en: translateInterface } = {
    "bn": {
        "search": "সার্চ",
        "go_back": "ফিরে যান",
        "browser_history": "ব্রাউজার ইতিহাস",
        "address_label": "ঠিকানা লেবেল",
        "home": "বাড়ি",
        "wishlist": "ইচ্ছে তালিকা",
        "enter_valid_info_of_area_address": "এলাকার ঠিকানার বৈধ তথ্য লিখুন",
        "cart": "কার্ট",
        "profile": "প্রোফাইল",
        "account_information": "অ্যাকাউন্ট তথ্য",
        "notifications": "নোটিফিকেশন",
        "my_orders": "আমার অর্ডার",
        "my_carts": "আমার কার্ট",
        "my_wishlists": "আমার ইচ্ছে তালিকা",
        "shipping_address": "শিপিং অ্যাড্রেস",
        "support_tickets": "সাপোর্ট টিকেট",
        "my_profile": "আমার প্রোফাইল",
        "settings": "সেটিংস",
        "log_out": "লগ আউট",
        "name": "নাম",
        "email": "ইমেইল",
        "balance": "ভারসাম্য",
        "birthday": "জন্মদিন",
        "country": "দেশ",
        "default_shipping_address": "ডিফল্ট শিপিং ঠিকানা",
        "select_area": "এরিয়া সিলেক্ট করুন",
        "select_city": "শহর সিলেক্ট করুন",
        "gender": "লিঙ্গ",
        "is_block": "is_block",
        "last_login": "শেষ লগইন",
        "phone": "ফোন",
        "courier_service_address": "কুরিয়ার সার্ভিসের ঠিকানা",
        "registered": "নিবন্ধিত",
        "reward_coins": "reward_coins",
        "user_id": "ব্যবহারকারী আইডি",
        "user_type": "ব্যবহারকারীর ধরন",
        "update": "আপডেট করুন",
        "change_language": "ভাষা পরিবর্তন করুন",
        "details": "বিস্তারিত",
        "tracking_number": "ট্র্যাকিং নম্বর",
        "total_amount": "মোট পরিমাণ",
        "buy_now": "এখন কিনুন",
        "courier_address": "কুরিয়ার ঠিকানা",
        "alternate_phone_number": "অন্য আর একটি ফোন নাম্বার",
        "default_address": "ডিফল্ট",
        "do_you_want_to_exit": "আপনি কি প্রস্থান করতে চান",

        "privacy_policy": "গোপনীয়তা এবং নীতি",
        "by_signing_up_i_agree_to_the_terms_and_privacy_policy": "নতুন একাউন্ট তৈরী করার মাধ্যমে  আমি শর্তাবলী এবং গোপনীয়তা নীতিতে সম্মত",
        "terms": "শর্তাবলী",
        "cancel": "ক্যানসেল",
        "exit": "বাহির হবো",

        "sign_in": "প্রবেশ করুন",
        "sign_up": "একাউন্ট তৈরি করুন",
        "already_have_account": "ইতিমধ্যে অ্যাকাউন্ট আছে",
        "password_error": "ন্যূনতম আটটি অক্ষর, অন্তত একটি অক্ষর এবং একটি সংখ্যা",
        "new_here": "এখানে নতুন",
        "email_error": "বৈধ ইমেইল প্রবেশ করান ",
        "password": "পাসওয়ার্ড",
        "forget_my_password": "পাসওয়ার্ড ভুলে গেছি",
        "name_error": "অনুগ্রহ করে বৈধ নাম ইনপুট করুন",
        "phone_error": "একটি বৈধ ফোন নম্বর ইনপুট করুন",
        "add_new_address": "নতুন ঠিকানা যোগ করুন",
        "area_address": " এরিয়া ঠিকানা",
        "no_results_found": "কোনো ফলাফল খুঁজে পাওয়া যায়নি",
        "search_for_something": "কিছু সার্চ করুন",

    },

    "en": {
        "search": "Search",
        "no_results_found": "No results found",
        "add_new_address": "Add New Address",
        "home": "Home",
        "courier_service_address": "Courier service address",
        "browser_history": "Browser History",
        "wishlist": "Wishlist",
        "area_address": "Area Address",
        "search_for_something": "Search for something",
        "cart": "Cart",
        "profile": "Profile",
        "go_back": "Back",
        "account_information": "Account Information",
        "notifications": "Notifications",
        "my_orders": "My Orders",
        "my_carts": "My Carts",
        "my_wishlists": "My Wishlists",
        "shipping_address": "Shipping Address",
        "support_tickets": "Support Tickets",
        "my_profile": "My Profile",
        "settings": "Settings",
        "log_out": "Log out",
        "name": "Name",
        "select_area": "Select area",
        "select_city": "Select city",
        "email": "Email",
        "balance": "Balance",
        "birthday": "Birthday",
        "country": "Country",
        "default_shipping_address": "default_shipping_address",
        "gender": "Gender",
        "address_label": "Address label",
        "cancel": "Cancel",
        "alternate_phone_number": "Alternate phone number",
        "exit": "Exit",
        "do_you_want_to_exit": "Do you want to exit",
        "is_block": "is_block",
        "last_login": "last_login",
        "phone": "Phone",
        "registered": "Registered",
        "enter_valid_info_of_area_address": "Enter valid info of area address",
        "reward_coins": "Reward_coins",
        "user_id": "User_id",
        "user_type": "user_type",
        "change_language": "Change Language",
        "details": "Details",
        "privacy_policy": "Privacy policy",
        "tracking_number": "Tracking Number",
        "total_amount": "Total Amount",
        "buy_now": "Buy Now",
        "courier_address": "Courier Address",
        "default_address": "Default",
        "by_signing_up_i_agree_to_the_terms_and_privacy_policy": "By signing up I agree to the terms and privacy policy.",
        "terms": "Terms",


        "sign_in": "Sign In",
        "sign_up": "Create account",
        "already_have_account": "Already have account",
        "new_here": "New here",
        "password_error": "Minimum eight characters, at least one letter and one number",
        "email_error": "Please input valid email",
        "password": 'Password',
        "update": "Update",
        "forget_my_password": "Forget my password",
        "name_error": "Please input a valid name",
        "phone_error": "please input a valid phone number",
    }
}